---
- name: install mysql Server on vm2
  hosts: vm2
  become: yes
  become_method: sudo

  tasks:
    - name: install mysql-server
      ansible.builtin.yum:
        name: mysql-server
        state: latest

    - name: start and enable mysqld service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

